# Theme
remote_theme: daviddarnes/alembic@main

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# Meta
title: "YI Jian (易简)"
description: "YI Jian's personal webpage. | 这里是易简的个人网站。"
lang: en
timezone: Asia/Singapore
permalink: pretty
logo: "https://c-ssl.dtstatic.com/uploads/item/202004/22/20200422142756_tifum.thumb.400_400_c.jpg_webp"

# Navigation
navigation_header:
  - title: Home
    url: /
  - title: Pages
    url: /pages/
  - title: Blog
    url: /blog/

navigation_footer:
  - title: Back to top
    url: "#top"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: page


# Social links (optional)
twitter_username: liqiushui2427
github_username: LIQiushui2427
linkedin_username: yijian2427
  
