# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
  
title: "YI Jian (易简)"
description: "YI Jian's personal webpage. | 这里是易简的个人网站。"
lang: en
timezone: Asia/Singapore
permalink: pretty
logo: "https://c-ssl.dtstatic.com/uploads/item/202004/22/20200422142756_tifum.thumb.400_400_c.jpg_webp"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Pages
  url: /Pages/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Pages
    output: true
    description: "My collections"
    feature_text: |
      Here are YI Jian's favourites
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


# Social links (optional)
twitter_username: liqiushui2427
github_username: LIQiushui2427
linkedin_username: yijian2427
  
