remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-tactile
title: YI Jian (易简)
description: YI Jian's personal webpage。| 这里是易简的个人网站。