remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-tactile
# Meta
title: "YI Jian (易简)"
description: "YI Jian's personal webpage. | 这里是易简的个人网站。"
lang: en
timezone: Asia/Singapore
permalink: pretty
logo: "https://c-ssl.dtstatic.com/uploads/item/202004/22/20200422142756_tifum.thumb.400_400_c.jpg_webp"

collections:
  pages_content:
    output: true
    permalink: /pages/:name/
  blog_posts:
    output: true
    permalink: /blogs/:name/

defaults:
  - scope:
      path: ""
      type: pages_content
    values:
      layout: default
  - scope:
      path: ""
      type: blog_posts
    values:
      layout: default



# Social links (optional)
twitter_username: liqiushui2427
github_username: LIQiushui2427
linkedin_username: yijian2427
  
